package com.mast.readup.entities;

import java.time.LocalDate;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * This class represents the "sfida" (challenge) entity in the database.
 * It uses Lombok to reduce boilerplate code and JPA annotations for ORM
 * mapping.
 */

@Entity
@Table(name = "sfida")
@Data
@NoArgsConstructor // Lombok: Generates a no-argument constructor (required by JPA)
@AllArgsConstructor // Lombok: Generates a constructor with all fields
@EqualsAndHashCode(onlyExplicitlyIncluded = true) // Lombok: Limits equality to specified fields
public class Sfida {

    // Primary key class Sfida, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "codice_sfida")
    private int codiceSfida;

    // Challenge name
    @Column(name = "nome_sfida", length = 80, nullable = true)
    private String nomeSfida;

    // Challenge description
    @Column(name = "descrizione_sfida", length = 500, nullable = true)
    private String descrizioneSfida;

    // Number of challenge participants, required field
    @Column(name = "num_partecipanti", nullable = false)
    @NotNull
    private int numPartecipanti;

    // Start date of the challenge
    @Column(name = "data_inizio", nullable = false)
    @NotNull
    private LocalDate dataInizio;

    // End date of the challenge
    @Column(name = "data_fine", nullable = true)
    private LocalDate dataFine;

    // JSON field as a list of Strings
    @Column(name = "nome_partecipanti", columnDefinition = "json", nullable = true)
    @Convert(converter = JsonStringListConverter.class)
    private List<String> nomePartecipanti;
}
